name: Sync chinalist.txt

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch and update
      run: |
        rm -rf .git
        git clone https://github.com/LucienShui/chinalist.git -b ${{ secrets.DIST_BRANCH }} buf
        python main.py
        mv chinalist.txt buf
        cd buf
        git config user.name "Lucien Shui"
        git config user.email "lucien@lucien.ink"
        git add --all
        if ! git commit -m "Sync at `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"; then exit 0; fi
        git push https://"${{ secrets.GH_TOKEN}}"@"github.com/${{ github.repository }}.git" ${{ secrets.DIST_BRANCH }}
